<html>
<title> Mahendra's Demo App </title>
<body>
<?php
  $instance = shell_exec('curl -s http://metadata.google.internal/computeMetadata/v1/instance/name -H "Metadata-Flavor: Google"');
  $zone = shell_exec('curl -s http://metadata.google.internal/computeMetadata/v1/instance/zone -H "Metadata-Flavor: Google" | cut -d"/" -f 4');
?>
<center>
<br>
<IMG SRC="https://i.pcmag.com/imagery/reviews/02yVL9f8Jw1atwoG6sgFZDH-7..1569482492.jpg" ALT="Demo Logo" width="470" height="400"><br></c
enter>
<center><p style="font-family:verdana">This page was generated by instance <b><?= $instance ?></b> in Availability Zone <b><?= $zone ?></b>.</p></center>